version: '3.1'

services:
  postgres:
    restart: always
    image: postgres:10.5-alpine
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "multi-tenant"
    ports:
      - '5432:5432'
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
